### ISSUE TITLE
Send bikeshed and respec issue summary to spec-prod

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/speced-cg#27]
It would be nice to update the mailing list with what is happening with tooling on a weekly basis.

**Comment by ericprud** [comment]
Like with a digest or with a human-curated summary?

**Comment by marcoscaceres** [comment]
Basically, one of these https://github.com/w3c/github-notify-ml-config 

Which look like, for example:

![Screen Shot 2021-05-18 at 4 51 21 pm](https://user-images.githubusercontent.com/870154/118605136-48242480-b7f9-11eb-9951-dffc3fa62476.png)

In our case, we would just have ReSpec and BikeShed as the two listed repos.

**Comment by ericprud** [comment]
Your notify-ml-fu is stronger than mine. [ShEx subscription](https://github.com/w3c/github-notify-ml-config/blob/main/mls.json) just yields [separate messages](https://lists.w3.org/Archives/Public/public-shex-dev/2021Jan/thread.html). The above looks like some sort of git-sensitive digest. (sorry, a bit off-topic, but i'm interested to see what this tool can do.)

**Comment by marcoscaceres** [comment]
It's definitely possible to combine the output from different repos into a single email message. I'll ping you when I send the PR to actually do it.

**Comment by marcoscaceres** [comment]
@ericprud, finally got around to sending the PR: https://github.com/w3c/github-notify-ml-config/pull/217

**Comment by ericprud** [comment]
tx! [turfed decision](https://github.com/shexSpec/shex/issues/116) to ShEx CG.
